import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// UPDATE BAGIAN INI
export const metadata: Metadata = {
  title: "JEN.AI",
  description: "Generated by create next app",
  icons: {
    icon: "/8.png", // Next.js akan otomatis mencari file ini di folder 'public'
    shortcut: "/8.png", // Opsional: Untuk shortcut icon
    apple: "/8.png",    // Opsional: Untuk icon saat di-save di iPhone/iPad
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
